config/routes.rb
Rails.application.routes.draw do
  root to: "players#index"
  delete '/logout', to: 'users#delete'
  get 'auth/:provider/callback', to: 'users#create'
  get 'auth/failure', to: redirect('/')
  resources :players, except: [:show, :index]
  get '/admin', to: 'admin#index', as: 'admin'
  get '/admin/logs', to: 'admin#logs', as: 'admin_logs'
  get '/admin/users', to: 'admin#users', as: 'admin_users'
  get '/admin/users/:id/modification', to: 'admin#edit_user', as: 'admin_edit_user'
  resources :users, only: %i[edit update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  belongs_to :player
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  def self.find_or_create_from_auth_hash(auth)
		where(uid: auth.uid).first_or_initialize.tap do |user|
			user.uid = auth.uid
			user.email = auth.info.email
      user.username = auth.extra.raw_info.username
      user.discriminator = auth.extra.raw_info.discriminator
      user.avatar = auth.extra.raw_info.avatar
      user.save!
		end
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :admin?

  def logs
    if params[:query].present?
      @pagy, @logs = pagy(Log.search_by_user_or_action(params[:query]))
    else
      @pagy, @logs = pagy(Log.order(created_at: :desc))
    end
  end

  def users
    if params[:query].present?
      @pagy, @users = pagy(User.search_by_username_or_email(params[:query]))
    else
      @pagy, @users = pagy(User.order(created_at: :desc))
    end
  end

  def edit_user
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:valided, :admin)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  protect_from_forgery with: :exception
  helper_method :current_user
  helper_method :user_signed_in?
  include Pagy::Backend


  def authenticate
    redirect_to root_path, alert: "Connectez vous pour accéder à cette page." unless user_signed_in?
  end

  def admin?
    redirect_to root_path, alert: "Vous n'avez pas accès à cette page." unless current_user.admin
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  def user_signed_in?
    !!current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate, only: [ :home ]

  def home
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  skip_before_action :authenticate, only: [ :index ]

  require "uri"
  require "net/http"
  require 'resolv-replace'
  require 'cgi'
  require 'json'

  def index
    if params[:query].present?
      @pagy, @players = pagy(Player.search_by_uuid_or_username(params[:query]))
    else
      @pagy, @players = pagy(Player.order(created_at: :desc))
    end
  end

  def new
    @player = Player.new
  end

  def create
    my_hash = player_params.merge(wolfyApi(player_params[:uuid]))
    @player = Player.new(my_hash)
    @player.user = current_user
    @player_unique = Player.find_by(uuid: player_params[:uuid])
    if @player_unique.present?
      redirect_to root_path(query: player_params[:uuid]), alert: "Joueur déjà enregistré"
    else
      if wolfyApi(player_params[:uuid]).present?
        if @player.save
          Log.create(user: current_user, player: @player, action: "Enregistrement")
          redirect_to root_path(query: player_params[:uuid]), notice: "Joueur ajouté"
        else
          render "new", status: :unprocessable_entity
        end
      else
        redirect_to new_player_path, alert: "UUID invalide"
      end
    end
  end

  private

  def player_params
    params.require(:player).permit(:uuid)
  end

  def wolfyApi(uuid)
    url = URI("https://wolfy.net/api/leaderboard/player/#{CGI.escape(uuid)}")
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    request = Net::HTTP::Get.new(url)
    request["Cookie"] = ENV["WOLFY_COOKIE"]
    response = https.request(request)
    if response.code == "200"
      parse = JSON.parse(response.read_body)
      {
        username: parse["user"]["username"]
      }
    else
      return nil
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate, only: [:create]
  def create
    @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
  	session[:user_id] = @user.id
  	redirect_to root_path, notice: "Vous êtes connecté."
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: "Votre profil a été mis à jour."
    else
      render :edit
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to root_path, notice: "Vous êtes déconnecté."
  end

  private

  def user_params
    params.require(:user).permit(:valided, :admin)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def is_active?(link_path)
    current_page?(link_path) ? "active" : ""
  end

end

app/views/admin/edit_user.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :valided %>
  <%= f.input :admin %>
  <%= f.button :submit %>
<% end %>

app/views/admin/logs.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class="forms">
        <h2 class="text-center mt-3">Logs</h2>
          <%= form_tag @admin_logs_path, method: :get do %>
            <%= text_field_tag :query, params[:query], placeholder: "Rechercher...", class: "form-control"%>
              <br>
            <%= submit_tag "Chercher", class: "btn btn-success text-white" %>
          <% end %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">Action</th>
              <th scope="col">Joueur</th>
              <th scope="col">Par</th>
              <th scope="col">Date</th>
            </tr>
          </thead>
          <tbody>
          <% @logs.each do |log| %>
            <tr>
              <td><%= log.action %></td>
              <td><%= link_to log.player.username, root_path(query: log.player.uuid) %></td>
              <td><%= log.user.username %></td>
              <td><%= format_french_date(log.created_at) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class="forms">
        <h2 class="text-center mt-3">Utilisateurs</h2>
          <%= form_tag @admin_logs_path, method: :get do %>
            <%= text_field_tag :query, params[:query], placeholder: "Rechercher...", class: "form-control"%>
              <br>
            <%= submit_tag "Chercher", class: "btn btn-success text-white" %>
          <% end %>
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">Pseudo</th>
              <th scope="col">Email</th>
              <th scope="col">Validation</th>
            </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td><%= user.email %></td>
              <td><%= user.valided? ? "oui" : "non" %></td>
              <%= link_to "edit", admin_edit_user_path(user) %>
            </tr>
          <% end %>
          </tbody>
        </table>
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wolfi202</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/players/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class="forms">
        <h2 class="text-center mt-3">Joueurs enregistrés</h2>
        <% if user_signed_in? %>
          <%= form_tag @root_path, method: :get do %>
          <%= text_field_tag :query, params[:query], placeholder: "Rechercher...", class: "form-control"%>
            <br>
          <%= submit_tag "Chercher", class: "btn btn-success text-white" %>
        <% end %>
        <p><i class="fas fa-users"></i> Nombre de joueurs enregistrés : <strong><%= Player.count %></strong></p>
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">UUID</th>
              <th scope="col">Pseudo</th>
              <th scope="col">Avatar</th>
            </tr>
          </thead>
          <tbody>
          <% @players.each do |player| %>
            <tr>
              <td><%= player.uuid %></td>
              <td><%= player.username %></td>
              <td><%= image_tag "https://wolfy.net/api/skin/render/user.png?id=#{player.uuid}&v=WF9WABNRLH&profile=center", alt: "avatar", class: "avatar-wolfy" %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
        <%== pagy_bootstrap_nav(@pagy) %>
        <% else %>
          <p class="text-center">Vous devez être connecté pour accéder au contenu.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/players/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <div class="forms">
        <h2 class="text-center mt-3">Nouvel enregistrement</h2>
        <% if current_user.valided? || current_user.admin? %>
          <%= simple_form_for @player do |f| %>
            <%= f.input :uuid, class: "form-control", label: "Nouveau joueur" %>
            <%= f.button :submit, class: "btn btn-success text-white", value: "Enregistrer"%>
          <% end %>
          <% else %>
            <p class="text-center">Vous devez être validé pour accéder au contenu.</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% unless controller_name == "admin" %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to "#", class: "navbar-brand" do %>
        <%= image_tag "logo", class: "rounded-circle" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to root_path, class: "nav-link #{is_active?(root_path)}" do %>
              <i class="fas fa-search"></i> Joueurs enregistrés
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  new_player_path, class: "nav-link #{is_active?(new_player_path)}" do %>
                <i class="fas fa-user-plus"></i> Enregistrer un joueur
              <% end %>
            </li>
            <li class="nav-item dropdown">
              <%= image_tag "https://cdn.discordapp.com/avatars/#{current_user.uid}/#{current_user.avatar}", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Administration", admin_path, class: "dropdown-item" if current_user.admin? %>
                <%= button_to 'Déconnexion', logout_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= button_to "/auth/discord", data: {turbo_method: :post, turbo: :false}, class: "nav-link btn btn-primary text-white" do %>
                <i class="fab fa-discord"></i> Connexion
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">
      <%= link_to "Administration", admin_path, class: "navbar-brand" %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link #{is_active?(root_path)}" do %>
              <i class="fa-solid fa-gauge"></i> Dashboard
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to admin_logs_path, class: "nav-link #{is_active?(admin_logs_path)}" do %>
              <i class="fa-solid fa-clock-rotate-left"></i> Gestion des logs
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link #{is_active?(root_path)}" do %>
              <i class="fa-solid fa-users"></i> Gestion des joueurs
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to  admin_users_path, class: "nav-link #{is_active?(admin_users_path)}" do %>
              <i class="fa-solid fa-users-gear"></i> Gestion des utilisateurs
            <% end %>
          </li>
           <li class="nav-item">
            <%= link_to root_path, class: "nav-link #{is_active?(new_player_path)}" do %>
              <i class="fa-solid fa-house fa-lg"></i>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>